### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by taomasgonzalez** [taomasgonzalez/TP_FINAL#23]
## Falta por hacer

1) Hacer que no se corte en juego por paquetes de información (cuando se mandan muchos muy rapido). Esto tiene dos posibles causas:
		a) Maquina de estados, FSM, error logico y mal chequeo de movimientos en cuanto a rangos y turnos
		b) Posible perdida cronologica de los paquetes. En vez de llegar A, B, C en el orden que se mandaron, llega A, C, B
2) Que se pueda jugar mientras los enemigos se mueven

3) Hay movimientos que no estan hechos todavia, como la pelota moviendose o el personaje empujando
4) Logica del juego, esto incluye pero no esta limitado a: 
		a) Muertes
		b) Ganar y Perder
		c) Congelamiento de enemigos y rodar la pelota
		d) Cambiar de nivel
		
5) Jugabilidad. Hay que jugar mucho al juego y verificar que funcione. JUGARLO CON DOS COMPUTADORAS!!!
6) Hacer cambios a CharacterActionsFSM para que los movimientos sean continuos !

**Comment by gcbertachini** [comment]
1 y 6 solucionadao

**Comment by taomasgonzalez** [comment]
### To do list para el punto 2 - que se pueda jugar mientras los enemigos se mueven

- [x]  Hacer que se generen pocos enemy actions, solo para cuando se lo necesite (fijarse funcion is_iddle)
- [ ] Hacer que no tire exception cuando salta y el segundo sub-salto no tiene sentido
- [ ] Hacer que el player se muera cuando se choca con un enemigo
- [ ] Snowball, partially frozen y demas andando segun consigna.
